/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false functions/worker-configuration.d.ts` (hash: ce4c92cc9370246782078f89bda5bd79)
interface __BaseEnv_Env {
	SHOP_FILES: R2Bucket;
	COMMENTS_DB: D1Database;
	SHOP_DB: D1Database;
	COMMENT_ALLOWED_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net,homepage-hatt.pages.dev";
	COURSE_SIGNUP_EMAIL_FROM: "Hattのホームページ <noreply@hatt.acecore.net>";
	COURSE_SIGNUP_EMAIL_TO: "borubin@outlook.jp";
	SHOP_CONTACT_EMAIL_FROM: "Hatt shop <noreply@hatt.acecore.net>";
	SHOP_CONTACT_EMAIL_TO: "borubin@outlook.jp";
	SHOP_ACCESS_TEAM_DOMAIN: "https://acecore.cloudflareaccess.com";
	SHOP_ACCESS_AUD: "12faf91ff5d66812272272ec869557e4367f7f0a48cb1447f37e4b9e34de9e84";
	SHOP_ACCESS_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net,homepage-hatt.pages.dev,*.homepage-hatt.pages.dev";
	SHOP_DISCLOSURE_ENABLED: "true";
	SHOP_DISCLOSURE_ALLOWED_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net";
	SHOP_DISCLOSURE_TURNSTILE_SITE_KEY: "0x4AAAAAADgFdX0i7Etno1bL";
	CMS_ACCESS_ALLOWED_EMAILS: string;
	CMS_GITHUB_APP_CLIENT_ID: string;
	CMS_GITHUB_APP_INSTALLATION_ID: string;
	CMS_GITHUB_APP_PRIVATE_KEY: string;
	COMMENT_HASH_SALT: string;
	TURNSTILE_SECRET_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	SHOP_DOWNLOAD_TOKEN_SECRET: string;
	SHOP_DISCLOSURE_HMAC_SECRET: string;
	SHOP_DISCLOSURE_SERVICE_TOKEN: string;
	COURSE_EMAIL_SERVICE: Fetcher /* homepage-hatt-course-email */;
	DISCLOSURE_EMAIL_SERVICE: Fetcher /* homepage-hatt-disclosure-email */;
	CMS_AI: Fetcher /* cms-ai */;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		SHOP_FILES: R2Bucket;
		COMMENTS_DB: D1Database;
		SHOP_DB: D1Database;
		COMMENT_ALLOWED_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net,homepage-hatt.pages.dev";
		COURSE_SIGNUP_EMAIL_FROM: "Hattのホームページ <noreply@hatt.acecore.net>";
		COURSE_SIGNUP_EMAIL_TO: "borubin@outlook.jp";
		SHOP_CONTACT_EMAIL_FROM: "Hatt shop <noreply@hatt.acecore.net>";
		SHOP_CONTACT_EMAIL_TO: "borubin@outlook.jp";
		SHOP_ACCESS_TEAM_DOMAIN: "https://acecore.cloudflareaccess.com";
		SHOP_ACCESS_AUD: "12faf91ff5d66812272272ec869557e4367f7f0a48cb1447f37e4b9e34de9e84";
		SHOP_ACCESS_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net,homepage-hatt.pages.dev,*.homepage-hatt.pages.dev";
		SHOP_DISCLOSURE_ENABLED: "true";
		SHOP_DISCLOSURE_ALLOWED_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net";
		SHOP_DISCLOSURE_TURNSTILE_SITE_KEY: "0x4AAAAAADgFdX0i7Etno1bL";
		CMS_ACCESS_ALLOWED_EMAILS: string;
		CMS_GITHUB_APP_CLIENT_ID: string;
		CMS_GITHUB_APP_INSTALLATION_ID: string;
		CMS_GITHUB_APP_PRIVATE_KEY: string;
		COMMENT_HASH_SALT: string;
		TURNSTILE_SECRET_KEY: string;
		STRIPE_SECRET_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		SHOP_DOWNLOAD_TOKEN_SECRET: string;
		SHOP_DISCLOSURE_HMAC_SECRET: string;
		SHOP_DISCLOSURE_SERVICE_TOKEN: string;
		COURSE_EMAIL_SERVICE: Fetcher /* homepage-hatt-course-email */;
		DISCLOSURE_EMAIL_SERVICE: Fetcher /* homepage-hatt-disclosure-email */;
		CMS_AI: Fetcher /* cms-ai */;
	}
	interface ProductionEnv {
		SHOP_FILES: R2Bucket;
		COMMENTS_DB: D1Database;
		SHOP_DB: D1Database;
		COMMENT_ALLOWED_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net,homepage-hatt.pages.dev";
		COURSE_SIGNUP_EMAIL_FROM: "Hattのホームページ <noreply@hatt.acecore.net>";
		COURSE_SIGNUP_EMAIL_TO: "borubin@outlook.jp";
		SHOP_CONTACT_EMAIL_FROM: "Hatt shop <noreply@hatt.acecore.net>";
		SHOP_CONTACT_EMAIL_TO: "borubin@outlook.jp";
		SHOP_ACCESS_TEAM_DOMAIN: "https://acecore.cloudflareaccess.com";
		SHOP_ACCESS_AUD: "12faf91ff5d66812272272ec869557e4367f7f0a48cb1447f37e4b9e34de9e84";
		SHOP_ACCESS_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net,homepage-hatt.pages.dev,*.homepage-hatt.pages.dev";
		SHOP_DISCLOSURE_ENABLED: "true";
		SHOP_DISCLOSURE_ALLOWED_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net";
		SHOP_DISCLOSURE_TURNSTILE_SITE_KEY: "0x4AAAAAADgFdX0i7Etno1bL";
		CMS_ACCESS_ALLOWED_EMAILS: string;
		CMS_GITHUB_APP_CLIENT_ID: string;
		CMS_GITHUB_APP_INSTALLATION_ID: string;
		CMS_GITHUB_APP_PRIVATE_KEY: string;
		COMMENT_HASH_SALT: string;
		TURNSTILE_SECRET_KEY: string;
		STRIPE_SECRET_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		SHOP_DOWNLOAD_TOKEN_SECRET: string;
		SHOP_DISCLOSURE_HMAC_SECRET: string;
		SHOP_DISCLOSURE_SERVICE_TOKEN: string;
		COURSE_EMAIL_SERVICE: Fetcher /* homepage-hatt-course-email */;
		DISCLOSURE_EMAIL_SERVICE: Fetcher /* homepage-hatt-disclosure-email */;
		CMS_AI: Fetcher /* cms-ai */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
