/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false functions/worker-configuration.d.ts` (hash: 8ae956edb42cebd0c0c86eb68ee44f8b)
interface __BaseEnv_Env {
	COMMENTS_DB: D1Database;
	COMMENT_ALLOWED_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net,homepage-hatt.pages.dev";
	COURSE_SIGNUP_EMAIL_FROM: "Hattのホームページ <noreply@hatt.acecore.net>";
	COURSE_SIGNUP_EMAIL_TO: "borubin@outlook.jp";
	CMS_ACCESS_ALLOWED_EMAILS: string;
	CMS_GITHUB_APP_CLIENT_ID: string;
	CMS_GITHUB_APP_INSTALLATION_ID: string;
	CMS_GITHUB_APP_PRIVATE_KEY: string;
	COMMENT_HASH_SALT: string;
	TURNSTILE_SECRET_KEY: string;
	COURSE_EMAIL_SERVICE: Fetcher /* homepage-hatt-course-email */;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		COMMENTS_DB: D1Database;
		COMMENT_ALLOWED_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net,homepage-hatt.pages.dev";
		COURSE_SIGNUP_EMAIL_FROM: "Hattのホームページ <noreply@hatt.acecore.net>";
		COURSE_SIGNUP_EMAIL_TO: "borubin@outlook.jp";
		CMS_ACCESS_ALLOWED_EMAILS: string;
		CMS_GITHUB_APP_CLIENT_ID: string;
		CMS_GITHUB_APP_INSTALLATION_ID: string;
		CMS_GITHUB_APP_PRIVATE_KEY: string;
		COMMENT_HASH_SALT: string;
		TURNSTILE_SECRET_KEY: string;
		COURSE_EMAIL_SERVICE: Fetcher /* homepage-hatt-course-email */;
	}
	interface ProductionEnv {
		COMMENTS_DB: D1Database;
		COMMENT_ALLOWED_HOSTNAMES: "hatt.acecore.net,www.hatt.acecore.net,homepage-hatt.pages.dev";
		COURSE_SIGNUP_EMAIL_FROM: "Hattのホームページ <noreply@hatt.acecore.net>";
		COURSE_SIGNUP_EMAIL_TO: "borubin@outlook.jp";
		CMS_ACCESS_ALLOWED_EMAILS: string;
		CMS_GITHUB_APP_CLIENT_ID: string;
		CMS_GITHUB_APP_INSTALLATION_ID: string;
		CMS_GITHUB_APP_PRIVATE_KEY: string;
		COMMENT_HASH_SALT: string;
		TURNSTILE_SECRET_KEY: string;
		COURSE_EMAIL_SERVICE: Fetcher /* homepage-hatt-course-email */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
