/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/course-email-service/wrangler.jsonc --include-runtime=false workers/course-email-service/worker-configuration.d.ts` (hash: 5dd375f2be82f2715dd4cc8b9b883bc4)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
