/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/disclosure-email-service/wrangler.jsonc --include-runtime=false workers/disclosure-email-service/worker-configuration.d.ts` (hash: 2676b1a594c8507999e5487a52d5840e)
interface __BaseEnv_Env {
  EMAIL: SendEmail
  DISCLOSURE_FROM_ADDRESS: 'noreply@hatt.acecore.net'
  DISCLOSURE_SERVICE_TOKEN: string
  DISCLOSURE_LEGAL_DETAILS_JSON: string
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index')
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
