/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/disclosure-email-service/wrangler.jsonc --include-runtime=false workers/disclosure-email-service/worker-configuration.d.ts` (hash: 8e5ff61ebf1b3ab5751aba4a61e9e369)
interface __BaseEnv_Env {
  EMAIL: SendEmail
  DISCLOSURE_SERVICE_TOKEN_STORE: SecretsStoreSecret
  DISCLOSURE_LEGAL_DETAILS_JSON_STORE: SecretsStoreSecret
  DISCLOSURE_FROM_ADDRESS: 'noreply@hatt.acecore.net'
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index')
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
